[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags = -DARDUINOJSON_USE_LONG_LONG=1

lib_deps =
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor
    mobizt/FirebaseClient @ 2.2.13
    bblanchon/ArduinoJson @ 7.4.3